---

# - name: create backend directory
#   become: yes
#   file:
#     path: /home/ubuntu/backend
#     state: directory
#     mode: 0755

# - name: copy backend files
#   become: yes
#   copy:
#     src: ~/project/artifact.tar.gz
#     dest: /home/ubuntu/backend/artifact.tar.gz

# - name: unpack backend files
#   become: yes
#   shell: |
#     cd /home/ubuntu/backend
#     tar -vxf artifact.tar.gz
#     rm -f artifact.tar.gz

# - name: start app server
#   become: yes
#   shell: |
#     cd /home/ubuntu/backend
#     npm install
#     pm2 stop default
#     pm2 start npm -- start


- name: create backend directory
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: "Move backend files to server."
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: "Install package dependencies"
  become: yes
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
    cd backend
    npm run build
    cd dist
    pm2 start npm --name backend -- start