---

- name: create backend directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: copy backend files
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: extract artifact.tar
  become: yes
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/
    remote_src: yes
    mode: 0755

- name: Install packages based on package.json.
  npm:
    path: ~/backend

- name: start app
  become: yes
  shell: |
    cd backend
    pm2 stop default
    pm2 start npm -- start