---

- name: "Move backend files to server."
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: "Install package dependencies"
  shell: |
    cd /home/ubuntu/backend
    tar -xzvf backend_artifact.tar.gz -C backend
    rm backend_artifact.tar.gz
    cd backend/
    npm run build
    cd dist
    pm2 start npm --name backend -- start
   